version: "3.8"

services:
    db:
        image: postgres:16.8-bullseye
        container_name: postgres_db
        environment:
            POSTGRES_USER: admin123
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: codebase
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/db_data:/var/lib/postgresql/data

volumes:
    db_data:
