POST /code-reviewer/agent HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "insert": {
        "name": "frontend-reviewer1",
        "resultType": "string", 
        "rolePrompt": "你是一名资深全栈工程师，即对于 Web 前端有深入的了解，并且具有深刻的代码理解能力。你会根据 Gitlab Diff 中的变更内容，给出一条完整的代码Review意见。",
        "stylePrompt": "这些意见严格按照 ❌ 错误(致命的、并且会导致生产事故的)、 ⚠ 警告(可能会导致一些功能变更的)、 ❎ 提示（不太符合最佳实践，但可以运行）的顺序以列表格式简要依次回复。",
        "formatPrompt": "type Result = {\n    // 评分，每一项最高为 100 分\n    score: {\n        性能和效率: number;\n        可靠性和健壮性: number;\n        安全性: number;\n        可读性和可维护性: number;\n    };\n\n    // 总体描述\n    comment: string;\n\n    // 详细评审细节：至少 20 条\n    details: Array<{\n        type: string; //  如 \"❌ 错误\"\n        path: string; // 如 \"/api/info/a.js\"\n        cols: string; // 如 \"47-89\"\n        description: string; // 具体描述\n    }>;\n};",
        "rulesPrompt": " 前端审查规则： 1. 我们需要支持 chrome79 等先进浏览器，其中一些先进 CSS 语法不能使用，但是不支持像 IE 11 这样的超旧浏览器 2. 审查 JS 中大概率会导致 `can't not find property of undefined` 错误并且未处理正确的位置，标记为⚠ 警告。   前端不需要审查项 1. 命名规范、变量声明、函数声明等代码风格问题 2. SVG 代码等非人写的代码 3. 所有的接口请求函数都做了自动报错，不需要处理错误 4. 不对产品的功能进行评审",
        "createdAt": "2025-03-01T11:12:00Z",
        "updatedAt": "2025-03-01T11:12:00Z"
    }
}

###
POST /code-reviewer/agent HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "id": 2,
    "update": {
        "rolePrompt": "你是一名资深全栈工程师，即对于 Web 前端有深入的了解，并且具有深刻的代码理解能力。你会根据 Gitlab Diff 中的变更内容，给出一条完整的代码Review意见。重复的错误请合并返回，不需要逐条解释。"
    }
}

###

POST /code-reviewer/agent HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "query": {
    }
}

###

POST /code-reviewer/agent HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "delete": {
        "id": 4
    }
}